### ISSUE TITLE
Specific component should be tagged with validation error

### ISSUE THREAD

**Issue by mdrillin** [debezium/debezium-ui-poc#281] opened 2021-01-18 20:07 UTC
Upon validation error, the error should be indicated on the specific component if the property name is available in the error.  This would allow the user to more easily identify the problem component.  In the example below, an error should be indicated on the "Connection attempt limit" entry input component.

![PropertyError](https://user-images.githubusercontent.com/1820403/104958632-fe841400-5995-11eb-8b6f-748454395236.png)

**Comment by indraraj** [comment] 2021-01-25 13:23
Hey @rk3rn3r, I am using the `propertyValidationResults[i].property` to verify/catch the problematic field but in the case of Postgres connector even if am passing incorrect `Password` or `Database` I am getting `property: "database.hostname"`

**Comment by indraraj** [comment] 2021-01-25 14:13
Hey @mdrillin should we also show the error msg in the helper text along with identifying invalid fields like https://patternfly-react.surge.sh/components/form#invalid or just to identify the invalid filed as the error msg is already present at the bottom(below screenshot)? 
![image](https://user-images.githubusercontent.com/8264372/105716818-5e099300-5f45-11eb-93a9-1c143abaac91.png)

**Comment by mdrillin** [comment] 2021-01-25 14:27
@indraraj I was thinking the specific error message could go directly underneath the component, as in the patternfly example.  The bottom message could then be changed to a more generic message.

**Comment by rk3rn3r** [comment] 2021-01-25 14:53
Hey @indraraj! I think the reason for this is that any error in the fields with the `database.` prefix, at least hostname, username, password, (but also SSL etc) can't yet be differentiated because any error leads to that we are unable to connect and this falls back to an error on assigned to the first field in row which is the hostname.
I created https://issues.redhat.com/browse/DBZ-2971 for better error reporting.

**Comment by indraraj** [comment] 2021-01-25 14:53
> @indraraj I was thinking the specific error message could go directly underneath the component, as in the patternfly example. The bottom message could then be changed to a more generic message.

Agree

**Comment by indraraj** [comment] 2021-01-25 15:02
> Hey @indraraj! I think the reason for this is that any error in the fields with the `database.` prefix, at least hostname, username, password, (but also SSL etc) can't yet be differentiated because any error leads to that we are unable to connect and this falls back to an error on assigned to the first field in row which is the hostname.
> I created https://issues.redhat.com/browse/DBZ-2971 for better error reporting.
> 
> It might be that we need to add a global `database.connection` field though for cases where we can't identify the cause of the connection issue.

@rk3rn3r so for the above-mentioned fields where we can't identify the cause `property: "database.connection"` will be returned instead of current `database.hostname`. correct me if I am wrong.

**Closed** 2021-01-27 16:29 UTC

**Comment by rk3rn3r** [comment] 2021-01-28 12:12
@indraraj I can't tell you now. I need to work on the mentioned task before I have an idea what's possible and what's not and if we need such a global field for connection errors. Sorry.

**Comment by indraraj** [comment] 2021-01-28 12:21
> @indraraj I can't tell you now. I need to work on the mentioned task before I have an idea what's possible and what's not and if we need such a global field for connection errors. Sorry.

Np @rk3rn3r , I have pushed the implementation for this fix in general. We can pick this up later for these fields if needed.
